apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: estudos
type: Opaque
stringData:
  # Dados do Banco
  DB_NAME: "banco_questoes"
  DB_USER: "usuario_questoes"
  DB_PASSWORD: "senha_super_segura_123"
  DB_HOST: "postgres-db"
  # Dados do Django
  SECRET_KEY: "django-insecure-chave-k8s-prod"
  DEBUG: "True"