apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: estudos
type: Opaque
stringData:
  DB_NAME: "banco_questoes"
  DB_USER: "usuario_questoes"
  DB_PASSWORD: "senha_forte"
  DB_HOST: "postgres-db"
  SECRET_KEY: "django-insecure-key"
  DEBUG: "True"